name: tf_2.4
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - ca-certificates=2020.12.8
  - certifi=2020.12.5
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - ncurses=6.2
  - openssl=1.1.1i
  - pip=20.3.3
  - python=3.7.9
  - readline=8.0
  - setuptools=51.1.2
  - sqlite=3.33.0
  - tk=8.6.10
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - absl-py==0.10.0
    - aiohttp==3.7.3
    - aiohttp-cors==0.7.0
    - aioredis==1.3.1
    - argon2-cffi==20.1.0
    - astunparse==1.6.3
    - async-generator==1.10
    - async-timeout==3.0.1
    - attrs==20.3.0
    - backcall==0.2.0
    - bleach==3.2.1
    - blessings==1.7
    - bokeh==2.2.3
    - bottleneck==1.3.2
    - cachetools==4.2.0
    - catkin-pkg==0.4.23
    - cffi==1.14.4
    - cftime==1.3.0
    - chardet==3.0.4
    - click==7.1.2
    - cloudpickle==1.6.0
    - colorama==0.4.4
    - colorful==0.5.4
    - cycler==0.10.0
    - dask==2020.12.0
    - decorator==4.4.2
    - defusedxml==0.6.0
    - dill==0.3.3
    - distributed==2020.12.0
    - distro==1.5.0
    - docutils==0.16
    - entrypoints==0.3
    - filelock==3.0.12
    - flatbuffers==1.12
    - fsspec==0.8.5
    - future==0.18.2
    - gast==0.3.3
    - google-api-core==1.26.0
    - google-auth==1.24.0
    - google-auth-oauthlib==0.4.2
    - google-pasta==0.2.0
    - googleapis-common-protos==1.52.0
    - gpustat==0.6.0
    - grpcio==1.32.0
    - h5py==2.10.0
    - heapdict==1.0.1
    - hiredis==1.1.0
    - idna==2.10
    - importlib-metadata==3.4.0
    - importlib-resources==5.0.0
    - ipykernel==5.4.3
    - ipython==7.19.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.3
    - jedi==0.18.0
    - jinja2==2.11.2
    - joblib==1.0.0
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.11
    - jupyter-console==6.2.0
    - jupyter-core==4.7.0
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.1
    - locket==0.2.0
    - markdown==3.3.3
    - markupsafe==1.1.1
    - matplotlib==3.3.3
    - mistune==0.8.4
    - msgpack==1.0.2
    - multidict==5.1.0
    - nbclient==0.5.1
    - nbconvert==6.0.7
    - nbformat==5.1.1
    - nest-asyncio==1.4.3
    - netcdf4==1.5.5.1
    - notebook==6.2.0
    - numpy==1.19.5
    - nvidia-ml-py3==7.352.0
    - oauthlib==3.1.0
    - opencensus==0.7.12
    - opencensus-context==0.1.2
    - opencv-python==4.5.1.48
    - opt-einsum==3.3.0
    - packaging==20.8
    - pandas==1.2.0
    - pandocfilters==1.4.3
    - parso==0.8.1
    - partd==1.1.0
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==7.2.0
    - prometheus-client==0.9.0
    - promise==2.3
    - prompt-toolkit==3.0.10
    - protobuf==3.14.0
    - psutil==5.8.0
    - ptyprocess==0.7.0
    - py-spy==0.3.4
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - pyglet==1.5.0
    - pygments==2.7.4
    - pyparsing==2.4.7
    - pyrsistent==0.17.3
    - python-dateutil==2.8.1
    - pytz==2020.5
    - pyyaml==5.3.1
    - pyzmq==21.0.0
    - qtconsole==5.0.1
    - qtpy==1.9.0
    - ray==1.2.0
    - redis==3.5.3
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rospkg==1.2.10
    - rsa==4.7
    - scikit-learn==0.24.0
    - scipy==1.6.0
    - seaborn==0.11.1
    - send2trash==1.5.0
    - six==1.15.0
    - sklearn==0.0
    - sortedcontainers==2.3.0
    - tabulate==0.8.9
    - tblib==1.7.0
    - tensorboard==2.4.0
    - tensorboard-plugin-wit==1.7.0
    - tensorflow==2.4.0
    - tensorflow-datasets==4.2.0
    - tensorflow-estimator==2.4.0
    - tensorflow-io==0.17.0
    - tensorflow-metadata==0.26.0
    - termcolor==1.1.0
    - terminado==0.9.2
    - testpath==0.4.4
    - threadpoolctl==2.1.0
    - toolz==0.11.1
    - tornado==6.1
    - tqdm==4.56.0
    - traitlets==5.0.5
    - typing-extensions==3.7.4.3
    - urllib3==1.26.2
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - werkzeug==1.0.1
    - widgetsnbextension==3.5.1
    - wrapt==1.12.1
    - xarray==0.16.2
    - yarl==1.6.3
    - zict==2.0.0
    - zipp==3.4.0
